---
title: "Exercice BDR et SQL"
description: "Exercice d'apprentissage du SQL"
author: "Ludovic Deneuville"
format: 
  html:
    toc: true
    toc-location: left
    toc-expand: 3
from: markdown+emoji
number-sections: true
number-depth: 3
---

## Objectif {.unnumbered}

Dans ce TP, vous allez :

- créer une base de données : lancer un service *PostgreSQL*
- vous connecter à cette base de données : utiliser un service *cloudBeaver*
- insérer des données via un script SQL
- écrire les requêtes SQL pour répondre aux questions

## Mise en place

### Lancer les services

- [ ] Connectez-vous au [SSPCloud](https://www.sspcloud.fr/){target="_blank"}
- [ ] Lancez un service **PostgreSQL**
- [ ] Lancez un service **Cloudbeaver**
- [ ] Ouvrez cloudBeaver
  - username : user-<username>
  - password : collez votre mot de passe

::: {.callout-tip title="Kesako"}
- PostgreSQL : Base de données
- Cloudbeaver : Logiciel pour communiquer avec une base de données

Il est possible de se connecter directement à une base de données, mais beaucoup plus simple d'utiliser un outil tel cloudBeaver.
:::

### Créer une connexion

Normalement si vous lancez les deux services dans l'ordre, lors du lancement de cloudBeaver, la base de données PostgreSQL est détectée et la connexion créée automatiquement.

Est-ce que la connexion a été créée ?

- Si oui, elle apparait à gauche dans cloudBeaver (liste des connexions)
- Si non, créez la connexion

::: {.callout-note title="Créer une connexion"}

- [ ] Commencez par ouvrir le README du service PostgreSQL
  - il contient les informations pour se connecter à la base de données
- [ ] Dans cloudBeaver > New connection
- [ ] Sélectionnez **PostgreSQL**
- [ ] Renseignez les champs suivants
  - Hostname : `postgresql-<...>`
  - Port : 5432
  - Database : defaultdb
  - Username : `user-<username>`
  - Password : `<password>`
- [ ] Cliquez sur TEST, puis sur [CREATE]{.blue-button}
:::

Une fois la connexion créée, ouvrez-là :

- [ ] Clic droit sur la connexion > Open
  - un petit rond vert apparait à côté

Enfin ouvrez un éditeur SQL pour écrire des requêtes :

- [ ] Clic droit > *SQL Editor*
- [ ] Vérifiez que vous êtes sous le profil `public@defaultdb`
  - En haut dans le bandeau bleu, sinon sélectionnez ce profil

### Insérer les données

- [ ] Copiez le contenu du fichier [echecs.sql](./exercice/echecs.sql){target="_blank"}
- [ ] Collez dans cloudBeaver
- [ ] Exécutez le script
  - Icone orange avec un parchemin contenant une flêche :scroll:

Si vous n'avez eu aucun message d'erreur, vérifiez la création des tables :

- [ ] Supprimez tout le script, une fois les tables créées, vous n'en avez plus besoin
- [ ] `SELECT * FROM echecs.tournoi;`
- [ ] Cliquez sur la flêche orange

::: {.callout-tip}
- Parchemin contenant une flêche (ALT+X) :arrow_right: exécuter toutes les requêtes de l'éditeur
- Flêche orange (CTRL+ENTREE) :arrow_right: exécuter la requête courante (là où est le curseur de la souris)
:::

### Alternatives

D'autres outils pour réaliser l'exercice :

- <https://onyxia.lab.groupe-genes.fr/>{target="_blank"} : fonctionne comme le SSP Cloud 
- DBeaver sur la VM ENSAI
  - Connectez-vous à la VM ENSAI
  - Lancez le logiciel Dbeaver
  - Paramétrez [DBeaver](../outils/DBeaver.qmd){target="_blank"}
- <https://sqliteonline.com/>{target="_blank"}
  - PostgreSQL > Click to connect
- <https://aiven.io/tools/pg-playground>{target="_blank"}


## Description des données

Nous avons une liste de **joueurs** et de **tournois**. Les joueurs peuvent participer aux différents tournois.

Un tournoi est supervisé par un **arbitre**. Un arbitre est un joueur qui a obtenu un **grade d'arbitre**.

Dans un tournoi, les parties se déroulent à une certaine **cadence** (Lente, Rapide, Blitz).



```{mermaid}
classDiagram
  class arbitre_grade {
    id_arbitre_grade: INT(PK)
    nom: VARCHAR
  }

  class joueur {
    id_joueur: INT(PK)
    pseudo: VARCHAR
    nom: VARCHAR
    prenom: VARCHAR
    elo: INT
    mail: VARCHAR
    id_arbitre_grade: INT(FK -> arbitre_grade)
  }

  class cadence {
    id_cadence: INT(PK)
    nom: VARCHAR
  }

  class tournoi {
    id_tournoi: INT(PK)
    id_arbitre: INT(FK -> joueur)
    nom: VARCHAR
    debut: DATE
    fin: DATE
    nb_rondes: INT
    id_cadence: INT(FK -> cadence)
  }

  class participant {
    id_tournoi: INT(FK -> tournoi)
    id_joueur: INT(FK -> joueur)
  }

  arbitre_grade -- joueur
  cadence -- tournoi
  tournoi -- participant
  joueur -- participant
```

## Questions

### Découverte des tables

- [ ] Listez tous les joueurs
- [ ] Faîtes de même sur les autres tables pour observer leur contenu
- [ ] Listez tous les joueurs ordonnés par elo descroissant
- [ ] Listez tous les joueurs ayant un elo inférieur ou égal à 2000
- [ ] Listez tous les joueurs ayant un elo inférieur ou égal à 2000 et dont le prénom contient un "e" (majuscule ou minuscule) 
  - :bulb: voir méthode UPPER

### Mise à jour

- [ ] Créez la joueuse : *Martine Dupont, elo : 1999, Arbitre Elite*
- [ ] Supprimez le joueur de pseudo *marc78*
- [ ] Essayez de supprimer le joueur ayant pour id : 20
  - Pourquoi cela ne fonctionne pas ? Que faudrait-t-il faire pour supprimer ce joueur ?
- [ ] Listez les joueurs qui sont arbitres 
  - :bulb: *voir IS NOT NULL*
- [ ] Ajoutez à la table joueur la colonne de type booléen *est_arbitre*
- [ ] Remplissez cette nouvelle colonne pour tous les joueurs

### Jointures 

- [ ] Listez les joueurs (nom, prénom) qui sont arbitres, ainsi que leur grade d'arbitre
- [ ] Listez tous les joueurs (nom, prénom) ainsi que leur grade d'arbitre s'ils le sont

### Agrégations

- [ ] Comptez le nombre de joueurs qui sont arbitres
- [ ] Comptez le nombre d'arbitres par grade
- [ ] Comptez le nombre d'arbitres par grade et n'afficher que si la moyenne elo des arbitres du grade est supérieure à 2000
- [ ] Affichez la liste des tournois (nom du tournoi, cadence, arbitre)
- [ ] Ajouter le nombre de joueurs et le elo max des joueurs

::: {.callout-tip title="Correction" collapse="true"}
Lien vers la [correction](./exercice/correction.sql)
:::