
project:
  type: website
  render:
    - "**/*.qmd"
    - "**/*.ipynb"

website:
  title: "Remise à Niveau Informatique"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: Premiers pas
        menu: 
          - href: doc/first-steps/datalab.qmd
            text: Datalab
          - href: doc/first-steps/git.qmd
            text: Git
      - text: SQL
        menu: 
          - href: doc/sql/sql-cours.qmd
            text: "Introduction à SQL"
          - href: doc/sql/sql-exercice.qmd
            text: "Exercice SQL"
      - text: Python
        menu: 
          - href: doc/python/python-cours.qmd
            text: "Introduction à Python"
          - href: doc/python/python-notebooks.qmd
            text: "Notebooks Python"
          - href: doc/python/01-types-et-variables.qmd
            text: "Types et Variables"
          - href: doc/python/02-listes-et-dictionnaires.qmd
            text: "Listes et Dictionnaires"
          - href: doc/python/03-tests-et-boucles.qmd
            text: "Tests et Boucles"
          - href: doc/python/04-fonctions.qmd
            text: "Fonctions"
          - href: doc/python/05-POO-introduction.qmd
            text: "Introduction à la POO"
          - href: doc/python/correction.qmd
            text: "Correction"
      - text: POO
        menu:
          - href: doc/POO/poo-cours.qmd
            text: "Introduction à la POO"
          - href: doc/POO/poo-exercice.qmd
            text: "Exercices POO"
      - href: doc/UML/UML.qmd
        text: UML
    right:
      - text: English
        menu: 
          - href: doc/english/home-en.qmd
            text: "Home"
          - href: doc/english/datalab-en.qmd
            text: "Datalab"
          - href: doc/english/git-en.qmd
            text: "Git"
          - href: doc/english/sql/sql-cours-en.qmd
            text: "SQL lesson"
          - href: doc/english/sql/sql-exercice-en.qmd
            text: "SQL exercice"
          - href: doc/english/python/python-cours-en.qmd
            text: "Python Lesson"
          - href: doc/english/python/python-notebooks-en.qmd
            text: "Python Notebooks"
          - href: doc/english/python/01-types-et-variables-en.qmd
            text: "Python Types and variables"
          - href: doc/english/python/02-listes-et-dictionnaires-en.qmd
            text: "Python List and Dictionaries"
          - href: doc/english/python/03-tests-et-boucles-en.qmd
            text: "Python Tests and Loops"
          - href: doc/english/python/04-fonctions-en.qmd
            text: "Python functions"
          - href: doc/english/python/05-POO-introduction-en.qmd
            text: "Python POO introduction"
          - href: doc/english/POO/poo-cours-en.qmd
            text: "POO Lesson"
          - href: doc/english/POO/poo-exercice-en.qmd
            text: "POO Exercices"
          - href: doc/english/uml-en.qmd
            text: "UML"
      - text: Examens
        menu: 
          - href: doc/annales/examen-2024.qmd
            text: "Examen 2024"
          - href: doc/annales/examen-2024-correction.qmd
            text: "Examen 2024 - correction"
          - href: doc/annales/examen-2025.qmd
            text: "Examen 2025"
          - href: doc/annales/examen-2025-correction.qmd
            text: "Examen 2025 - correction"
      - icon: github
        href: https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau
        target: "_blank"
  reader-mode: true
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Source code](https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau){.external target="_blank"}
  repo-url: https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau
  repo-branch: main
  issue-url: https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau/issues/new
  repo-actions: [edit, issue]

format:
  html:
    page-navigation: true
    theme: 
      dark: solar
      light: cosmo
    css: styles.css



