---
title: "Remise à niveau informatique"
description: "Remise à niveau pour les étudiants de l'ENSAI intégrés directement en 2e année"
author: "Ludovic Deneuville"
format: html
from: markdown+emoji
---

::: {.callout-important title="Pourquoi cette remise à niveau ?"}
Ce cours de remise à niveau s'adresse aux étudiants intégrant directement la deuxième année de l'ENSAI. Il s'agit d'un panorama des cours suivis par les étudiants en première année. 

**Le projet informatique démarre dès le début de la deuxième année.**

Il est donc essentiel pour tous d'avoir les bases en Python, POO, SQL et UML, afin de débuter le projet informatique en toute sérénité.

Ces enseignements sont à réaliser en autonomie. La charge de travail est estimée à 21h.
:::

## Pré-requis et Datalab

- [ ] Créer un compte sur [GitHub](https://github.com/){target="_blank"}
- [ ] Créer un compte sur le [SSP Cloud](https://datalab.sspcloud.fr/){target="_blank"}
  - avec votre mail `prenom.nom@eleve.ensai.fr`
- [ ] Lire cette page sur [Datalab](./doc/first-steps/datalab.qmd){target="_blank"}
- [ ] Créer un token en suivant les instructions ci-dessus
  - vous trouverez les infos [ici](https://ludo2ne.github.io/ENSAI-tools/doc/datalab/basics.html){target="_blank"}


## Programme

### Git

> 3h

Git est un système de gestion de versions qui permet de suivre les modifications apportées à des fichiers, de collaborer efficacement et de conserver l'historique d'un projet.

- [ ] Lire la [présentation de Git](https://ludo2ne.github.io/ENSAI-tools/doc/git/presentation.html){target="_blank"}
- [ ] TP rapide Git [cours d'introduction aux bases de données et à SQL](doc/first-steps/git.qmd)

### Initiation à SQL

> 3h

SQL (Structured Query Language) est le langage standard utilisé pour créer, interroger, modifier et administrer les bases de données relationnelles.

- [ ] Lisez le [cours d'introduction aux bases de données et à SQL](doc/sql/sql-cours.qmd)
- [ ] Faites l'exercice


### Initiation à Python

> 6h

Python est un langage de programmation polyvalent, simple à apprendre et largement utilisé pour le développement d'applications, l'analyse de données, l'intelligence artificielle et l'automatisation.

- [ ] Lisez le [cours d'introduction à Python](doc/python/python-cours.qmd)
- [ ] Lisez et faites les exercices des 5 notebooks


### Programmation Orientée Objet

> 9h

La POO est un paradigme de programmation qui consiste à modéliser un programme sous forme d'objets combinant des données (attributs) et des comportements (méthodes).

Vous pouvez commencer par créer un clone du dépôt Git sur votre machine :

- [ ] Ouvrez **Git Bash**, puis coller les commandes suivantes
  - `mkdir -p /p/Cours2A/UE3_Remise_a_niveau && cd $_`
  - `git clone https://github.com/ludo2ne/ENSAI-2A-remise-a-niveau.git`
  - cela crée une copie du dépôt dans *P:/Cours2A/UE3_Remise_a_niveau/ENSAI-2A-remise-a-niveau*

---

- [ ] Lisez le [cours d'introduction à la POO](doc/POO/poo-cours.qmd)
- [ ] Suivez les consignes pour le paramètrage de VSCode
- [ ] Faites les exercices


### UML

> 3h

UML est un langage de modélisation graphique permettant de représenter la structure et le comportement d'un système logiciel avant ou pendant son développement.

- [ ] Lisez le [cours d'introduction à UML](doc/UML/UML.qmd)
- [ ] Faites l'exercice


## Alternatives 

Voici d'autres possibilités pour se mettre à niveau en Python, POO et SQL

### Vidéos de la session 2022-2023

si vous avez vos accès à *MyENSAI*, les vidéos de la session de l'année 2022-2023 sont disponibles [ici](https://foad-moodle.ensai.fr/mod/url/view.php?id=11354){target="_blank"}


### Cours en ligne pour apprendre Python et SQL

- [Openclassrooms - Requêtez avecSQL](https://openclassrooms.com/fr/courses/7818671-requetez-une-base-de-donnees-avec-sql){target="_blank"}
- [Initiation à Python](https://inseefrlab.github.io/formation-python-initiation/){target="_blank"} dans le Service Statistique Public
- [Openclassrooms - bases de Python](https://openclassrooms.com/fr/courses/7168871-apprenez-les-bases-du-langage-python#table-of-content){target="_blank"} (parties 1 et 2)
- [Openclassrooms - POO avec Python](https://openclassrooms.com/fr/courses/7150616-apprenez-la-programmation-orientee-objet-avec-python){target="_blank"} (parties 1 et 2)
		

### Ressources utiles

- <https://realpython.com/>{target="_blank"}
- <https://refactoring.guru/>{target="_blank"}
- <https://github.com/faif/python-patterns>{target="_blank"}
- <https://inseefrlab.github.io/formation-bonnes-pratiques-git-R/>{target="_blank"}
- [Python pour la data science](https://pythonds.linogaliana.fr/){target="_blank"}, Lino Galiana (INSEE, ENSAE)