---
title: "Remise à niveau informatique"
description: "Remise à niveau pour les étudiants de l'ENSAI intégrés directement en 2e année (21h)"
author: "Ludovic Deneuville"
format: html
from: markdown+emoji
---

Ce cours de remise à niveau s'adresse aux étudiants intégrant directement la deuxième année de l'ENSAI. 
Il vise à fournir les bases essentielles en Python, SQL et UML, afin de leur permettre de débuter le projet informatique en toute sérénité.

## Programme

- [ ] [Bases de données et SQL](docs/sql/sql-cours.qmd) (3h)
- [ ] [Python - initiation](docs/python/python-cours.qmd) (6h)
- [ ] [Programmation Orientée Objet (POO)](docs/POO/POO.qmd) (9h)
- [ ] [UML](docs/UML/UML.qmd) (3h)
- [ ] Divers outils utiles (markdown, R, LateX...)


## 1. Initiation à SQL

- [ ] Lisez le [cours d'introduction aux bases de données et à SQL](docs/sql/sql-cours.qmd)
- [ ] Effectuez le paramètrage pour utiliser DBeaver
- [ ] Faites l'exercice


## 2. Initiation à Python

- [ ] Lisez le [cours d'introduction à Python](docs/python/python-cours.qmd)
- [ ] Lisez et faites les exercices des 5 notebooks


## 3. Programmation Orientée Objet


Vous pouvez commencer par créer un clone du dépôt Git sur votre machine :

- [ ] Ouvrez **Git Bash**, puis coller les commandes suivantes
  - `mkdir -p /p/Cours2A/UE3_Remise_a_niveau && cd $_`
  - `git clone https://github.com/ludo2ne/ENSAI-2A-remise-a-niveau.git`
  - cela crée une copie du dépôt dans *P:/Cours2A/UE3_Remise_a_niveau/ENSAI-2A-remise-a-niveau*

---

- [ ] Lisez le [cours d'introduction à la POO](docs/POO/POO.qmd)
- [ ] Suivez les consignes pour le paramètrage de VSCode
- [ ] Faites les exercices


## 4. UML

- [ ] Lisez le [cours d'introduction à UML](docs/UML/UML.qmd)
- [ ] Faites l'exercice


## Alternatives 

Voici d'autres possibilités pour se mettre à niveau en Python, POO et SQL

### Vidéos de la session 2022-2023

si vous avez vos accès à *MyENSAI*, les vidéos de la session de l'année 2022-2023 sont disponibles [ici](https://foad-moodle.ensai.fr/mod/url/view.php?id=11354){target="_blank"}


### Cours en ligne pour apprendre Python et SQL

- [SQL](https://openclassrooms.com/fr/courses/7818671-requetez-une-base-de-donnees-avec-sql){target="_blank"}
- [Python](https://openclassrooms.com/fr/courses/7168871-apprenez-les-bases-du-langage-python#table-of-content){target="_blank"} (parties 1 et 2)
- [POO avec Python](https://openclassrooms.com/fr/courses/7150616-apprenez-la-programmation-orientee-objet-avec-python){target="_blank"} (parties 1 et 2)
		

### Ressources utiles

- https://realpython.com/
- https://refactoring.guru/
- https://github.com/faif/python-patterns
- https://inseefrlab.github.io/formation-bonnes-pratiques-git-R/