---
title: "Python"
description: "Introduction à Python"
author: "Ludovic Deneuville"
format: 
  html:
    toc: true
    toc-location: left
    toc-expand: 3
from: markdown+emoji
number-sections: true
number-depth: 3
---

## Introduction {.unnumbered}

<!-- TODO : mettre au propre -->

Python est un langage de programmation. Connu pour sa simplicité et sa lisibilité, il est largement utilisé pour le développement web, la datascience, l'intelligence artificielle... Sa syntaxe claire facilite l'apprentissage, tandis que sa vaste communauté et ses bibliothèques robustes en font un choix populaire.

- Python
  - 1ère version en 1991
  - gratuit
  - multiplateforme (Linux, Windows...)
  - langage interprété
    - le script python est directement exécuté
    - pas de compilation
  - langage orienté objet
  - sensible à l'indentation (généralement 4 espaces)
    - utiliser un formatage automatique (autopep8)
- Version utilisée à l'ENSAI : 3.10.4
  - dernière version : 3.11.3
- Distribution utilisée à l'ENSAI
  - CPython
  - Autre distribution populaire : Anaconda
- IDE (Integrated Development Environment) utilisé à l'ENSAI
  - Visual Studio Code
  - Autres IDE : PyCharm, Jupyter, Atom, Spyder...
- Packages
  - Informatique
    - inquirerPy
    - requests
    - psycopg2-binary
    - tabulate
  - Datascience
    - NumPy
    - Pandas (manipulation et analyse des données, dataframe)
    - Matplotlib (graphiques 2D et 3D), Seaborn

---

- [ ] Ouvrir une invite de commandes **Git Bash**

```bash
python --version              # Python 3.10.4 
pip list                      # Packages installés
pip install <package_name>    # installer un package

# Distribution utilisée
python -c 'import platform; print(platform.python_implementation())'
```

## Utilisation des Notebooks

Pour découvrir Python, nous allons commencer par coder dans des Notebooks :

- [ ] [Les types et variables](01-types-et-variables.ipynb)
- [ ] [Les listes et dictionnaires](02-listes-et-dictionnaires.ipynb)
- [ ] [Les boucles](03-tests-et-boucles.ipynb)
- [ ] [Les fonctions](04-fonctions.ipynb)
- [ ] [Introduction à la Programmation Orientée Objet](05-POO-introduction.ipynb)


Pour utiliser les Notebooks :

- Télécharger les notebooks (plusieurs solutions)
  - télécharger ici : https://github.com/ludo2ne/ENSAI-2A-remise-a-niveau/tree/main/docs/python
  - sur chacune des notebooks, il y a en bas de la table des matières, un lien `Jupyter` pour télécharger le fichier *.ipynb*
  - si vous avez cloné le dépôt Git, allez dans *docs/python/*
- Se connecter à [Jupyter](https://clust-n4.ensai.fr/){.external target="_blank"} avec idxxxx et mot de passe
- Importer dans Jupyter les 5 fichiers `.ipynb`
  - pour importer, utiliser la flèche :arrow_up: en haut à gauche
- Ouvrir le premier notebook `01. types et variables.ipynb`
- Suivre les consignes et faire les exercices
- Faire de même avec les 4 autres notebooks

Autres possibilités pour utiliser des Notebooks :

- [Google Colab](https://colab.research.google.com/){.external target="_blank"}
- [SSPCloud](https://datalab.sspcloud.fr/){.external target="_blank"}

### Types de cellules

Un notebook est constitué de cellules. Vous pouvez créer une nouvelle cellule en cliquant sur le bouton `+` dans la barre d'outils.  
Il existe deux types de cellules principaux :

- les cellules de code (où vous écrivez et exécutez du code Python)
- les cellules de texte (où vous écrivez du texte formaté en utilisant Markdown)  

Le type de cellule souhaité est modifiable dans la barre d'outils.  

### Commandes utiles

| Commande                   | Description                                                                       |
| -------------------------- | --------------------------------------------------------------------------------- |
| `SHIFT + ENTER`            | Exécuter une cellule et passer à la suivante.                                     |
| `CTRL + ENTER`             | Exécuter une cellule sans passer à la suivante.                                   |
| `ESC`                      | Passer en mode commande (les bordures de cellule deviennent bleues).              |
| `ENTER`                    | Passer en mode édition (vous pouvez modifier le contenu de la cellule).           |
| `A`                        | Insérer une cellule au-dessus de la cellule courante.                             |
| `B`                        | Insérer une cellule en dessous de la cellule courante.                            |
| `D + D`                    | Supprimer une cellule.                                                            |


## Ressources utiles

<!-- TODO : mettre à jour -->

- <https://www.data-transitionnumerique.com/anaconda-python/>
- <https://github.com/ludo2ne/projet-info-2A>
- SSPCloud
  - initiation à Python
  - Python pour la datascience
  - initiation à Spark
  - initiation au Machine Learning
  - analyse textuelle
- [Python pour la data science](https://pythonds.linogaliana.fr/){.external target="_blank"}


## For fun

Chaque année en décembre, l'<a href="https://adventofcode.com/" target="_blank">AdventOfCode</a> occupe les développeurs
