<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Remise à Niveau Informatique</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Remise à Niveau Informatique</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-sql" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">SQL</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-sql">    
        <li>
    <a class="dropdown-item" href="../../docs/sql/sql.html">
 <span class="dropdown-text">Introduction à SQL</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/sql/DBeaver.html">
 <span class="dropdown-text">DBeaver</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-python" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Python</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-python">    
        <li>
    <a class="dropdown-item" href="../../docs/python/python.html">
 <span class="dropdown-text">Introduction à Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/python/01-types-et-variables.html">
 <span class="dropdown-text">Types et Variables</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/python/02-listes-et-dictionnaires.html">
 <span class="dropdown-text">Listes et Dictionnaires</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/python/03-tests-et-boucles.html">
 <span class="dropdown-text">Tests et Boucles</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/python/04-fonctions.html">
 <span class="dropdown-text">Fonctions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/python/05-POO-introduction.html">
 <span class="dropdown-text">Introduction à la POO</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../docs/POO/POO.html"> 
<span class="menu-text">POO</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../docs/UML/UML.html"> 
<span class="menu-text">UML</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-outils" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Outils</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-outils">    
        <li>
    <a class="dropdown-item" href="../../docs/outils/Git.html">
 <span class="dropdown-text">Git</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/outils/Git TP.html">
 <span class="dropdown-text">Git TP</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../docs/outils/VSCode.html">
 <span class="dropdown-text">Visual Studio Conde</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">




<section id="git-tp" class="level1">
<h1>Git TP</h1>
<p>Le but de ce TP est de :</p>
<ul class="task-list">
<li><label><input type="checkbox">vous présenter les fonctionnalités de base de Git</label></li>
<li><label><input type="checkbox">vous faire manipuler les 5 commandes principales (status, add, commit, pull, push)</label></li>
<li><label><input type="checkbox">vous montrer comment résoudre un conflit</label></li>
<li><label><input type="checkbox">bonus : retour en arrière, branches…</label></li>
</ul>
<section id="arrow_forward-1.-créer-un-projet" class="level2">
<h2 class="anchored" data-anchor-id="arrow_forward-1.-créer-un-projet">:arrow_forward: 1. Créer un projet</h2>
<p>:information_source: Ce projet permettra d’héberger le dépôt distant</p>
<ul>
<li>se connecter à <a href="https://gitlab.com/">GitLab</a></li>
<li>En haut à gauche, Menu &gt; Projects &gt; <a href="https://gitlab.com/projects/new">Create new project</a></li>
<li>Create blank project
<ul>
<li>Project name : <strong>git-tp</strong></li>
<li>Public</li>
<li><label><input type="checkbox" checked="">Initialize repository with a README</label></li>
<li>Create Project</li>
</ul></li>
</ul>
<hr>
<section id="small_orange_diamond-création-du-fichier-.gitignore" class="level3">
<h3 class="anchored" data-anchor-id="small_orange_diamond-création-du-fichier-.gitignore">:small_orange_diamond: Création du fichier .gitignore</h3>
<blockquote class="blockquote">
<p><strong>.gitignore</strong> est un fichier permettant de dire à Git quels fichiers il &gt; faut ignorer. Par exemple :</p>
<ul>
<li>si .gitignore contient <strong><code>*.csv</code></strong></li>
<li>et sur votre dépôt local, vous avez un fichier <strong><code>resultats.csv</code></strong></li>
<li>Git fera comme si ce fichier n’existe pas</li>
<li>Ainsi, ce fichier ne sera jamais poussé vers le dépôt distant</li>
</ul>
</blockquote>
<ul>
<li>Dans GitLab, sur la page de votre projet</li>
<li>Aller dans Repository &gt; Files</li>
<li>Au milieu , à droite de <code>git-tp/</code> cliquer sur l’icone :heavy_plus_sign:</li>
<li>New file</li>
<li>Select a template type : .gitignore</li>
<li>Apply a template : Python</li>
<li>Modifier le Commit message</li>
<li>Commit changes</li>
</ul>
<hr>
</section>
<section id="small_orange_diamond-inviter-dautres-membres" class="level3">
<h3 class="anchored" data-anchor-id="small_orange_diamond-inviter-dautres-membres">:small_orange_diamond: Inviter d’autres membres</h3>
<p>Vous venez de créer un projet public donc visible par tous. Cependant, vous êtes seul à pouvoir modifier ce projet. Pour autoriser d’autres personnes à écrire sur ce projet (par exemple lors du projet info), il faut donner les droits en écriture :</p>
<ul>
<li>Project informations &gt; Members &gt; Invite members</li>
<li>Role : Maintainer or Owner</li>
</ul>
<p>Cependant ce n’est pas nécessaire dans le cadre de ce TP, vous pouvez donc passer à la suite.</p>
<hr>
</section>
</section>
<section id="arrow_forward-2.-cloner-le-projet" class="level2">
<h2 class="anchored" data-anchor-id="arrow_forward-2.-cloner-le-projet">:arrow_forward: 2. Cloner le projet</h2>
<p>:information_source: Le but de cette étape est de créer votre dépôt local en faisant un clone du dépôt distant</p>
<ul>
<li>Ouvrir Visual Studio Code</li>
<li>Ouvrir un Terminal</li>
<li>Ouvrir un Terminal Git Bash
<ul>
<li>En haut à droite du terminal, à coté du <strong>+</strong>, cliquer sur la flèche vers le bas <strong>˅</strong></li>
</ul></li>
<li>Créer le dossier ci-dessous s’il n’existe pas déjà
<ul>
<li><code>mkdir "P:\Cours\Python"</code></li>
</ul></li>
<li>Se positionner dans ce dossier
<ul>
<li><code>cd "P:\Cours\Python"</code></li>
</ul></li>
<li>Cloner le projet
<ul>
<li><code>git clone git@gitlab.com:???????/git-tp.git</code>
<ul>
<li>Remplacer les <code>??????</code> par votre nom d’utilisateur GitLab</li>
<li>Ou sinon sur la page GitLab du projet
<ul>
<li>cliquer sur Clone</li>
<li>copier la ligne qui commence par <code>git@gitlab...</code></li>
</ul></li>
</ul></li>
<li><em>Are you sure you want to continue connecting (yes/no)?</em>
<ul>
<li>taper <code>yes</code> puis <code>ENTREE</code></li>
</ul></li>
<li>Votre dépôt local est maintenant créé</li>
</ul></li>
<li>Ouvrir ce dépôt dans l’explorateur VSCode
<ul>
<li>File &gt; Open Folder</li>
<li>git-tp</li>
</ul></li>
<li>Réouvrir le terminal Git Bash
<ul>
<li>Si ce n’est pas le cas, se positionner dans le dossier suivant :
<ul>
<li><code>cd "P:\Cours\Python\git-tp"</code></li>
</ul></li>
<li>un <strong>(main)</strong> apparait dans le terminal, cela signifie bien que vous êtes dans un dépôt Git</li>
</ul></li>
</ul>
<hr>
</section>
<section id="arrow_forward-3.-ajouter-un-nouveau-fichier" class="level2">
<h2 class="anchored" data-anchor-id="arrow_forward-3.-ajouter-un-nouveau-fichier">:arrow_forward: 3. Ajouter un nouveau fichier</h2>
<p>:information_source: Nous allons ici voir comment :</p>
<ul>
<li>ajouter/modifier des fichiers dans le dépôt local</li>
<li>envoyer ces mises à jour au dépôt distant</li>
</ul>
<p>Dans le dossier git-tp, créer un fichier <code>voiture.py</code> contenant le code suivant :</p>
<pre class="python="><code>class Voiture:
    
    def __init__(self, nom, couleur):
        self.couleur = couleur
        self.nom = nom
        self.vitesse = 0

    def accelere(self, increment):
        if increment &gt; 10:
            increment = 10
        self.vitesse = min(130, self.vitesse + increment)</code></pre>
<ul>
<li>Dans le terminal Git Bash, exécuter les commandes suivantes :</li>
<li><code>git status</code>
<ul>
<li>Le fichier apparait dans les <em>Untracked files</em></li>
<li>Cela siginifie que Git a repéré ce fichier mais pour le moment il ne le versionnera pas</li>
</ul></li>
<li><code>git add voiture.py</code>
<ul>
<li>pour dire à Git de suivre ce fichier</li>
</ul></li>
<li><code>git status</code>
<ul>
<li>maintenant le fichier est reconnu par Git</li>
</ul></li>
<li><code>git commit -m "creation classe voiture"</code>
<ul>
<li>pour créer un point de sauvegarde</li>
<li>Entre les <code>" "</code>, mettre un message court et explicite</li>
</ul></li>
<li><code>git status</code>
<ul>
<li><em>Your branch is ahead of ‘origin/main’ by 1 commit</em></li>
<li>Ce qui signifie que votre dépôt local est en avance d’un commit par rapport au dépôt distant</li>
</ul></li>
<li><code>git pull</code>
<ul>
<li><em>Already up to date</em></li>
<li>Pour vérifier que le dépôt distant n’a pas été mis à jour</li>
</ul></li>
<li><code>git push</code>
<ul>
<li>Vérifier qu’il n’y a pas d’erreur</li>
<li>Pour mettre à jour le dépôt distant avec mes modifications locales</li>
</ul></li>
</ul>
<p>:bulb: <strong>Combiner les commandes add et commit</strong></p>
<p>Dans le cas d’un nouveau fichier, il faut impérativement enchaîner les deux commandes suivantes pour que Git suive ce fichier :</p>
<ul>
<li><code>git add mon_fichier.py</code></li>
<li><code>git commit -m "Creation mon_fichier"</code></li>
</ul>
<p>Si le fichier existait déjà, il est possible de combiner les deux commandes :</p>
<ul>
<li>en ajoutant au commit un <strong>-a</strong> qui signifie add</li>
<li><code>git commit -am "Modification mon_fichier"</code></li>
</ul>
<p>:bulb: Si vous créez, non pas un mais plusieurs fichiers, vous pouvez utiliser la commande suivante pour tous les faire suivre par Git : <strong><code>git add .</code></strong></p>
<p>:bulb: Il est fortement recommandé de créer des commits très fréquement, par exemple</p>
<ul>
<li>Vous venez de modifier une fonction</li>
<li>Testez pour vérifier que votre code fonctionne bien</li>
<li>Créez un commit</li>
<li>Si jamais par la suite vous “cassez tout” et que plus rien ne marche, il est facile de revenir au dernier commit</li>
</ul>
<hr>
</section>
<section id="arrow_forward-4.-gérer-un-conflit" class="level2">
<h2 class="anchored" data-anchor-id="arrow_forward-4.-gérer-un-conflit">:arrow_forward: 4. Gérer un conflit</h2>
<blockquote class="blockquote">
<p>Dans le monde merveilleux de Git, tout se passe bien quand chacun &gt; travaille sur des fichiers différents. Lorsque deux personnes ont &gt; modifié le même fichier, ça peut se compliquer.</p>
<p>Au moment de la synchronisation des dépôts, Git va tenter de faire un &gt; auto-merge. Celui-ci fonctionnera bien si par exemple l’une des deux &gt; personnes a modifié le début du fichier et l’autre la fin.</p>
<p>Par contre, si les modifications concernent le même endroit, Git ne peut &gt; pas décider seul quelle est la bonne version et demande à l’utilisateur &gt; de choisir quelles lignes il souhaite conserver.</p>
</blockquote>
<p>Nous allons créer artificiellement un conflit, c’est à dire faire comme si 2 personnes avaient modifié le même fichier. Ce cas de figure arrivera inévitablement lorsque vous travaillerez à plusieurs sur un projet.</p>
<p>Il faut bien avoir en tête qu’un conflit :</p>
<ul>
<li>ce n’est pas grave</li>
<li>ce n’est pas une erreur</li>
<li>vous n’avez pas tout cassé</li>
<li>:scream: il ne faut pas paniquer, simplement savoir comment le résoudre</li>
</ul>
<hr>
<ul>
<li>Dans GitLab, cliquer sur le fichier <code>voiture.py</code></li>
<li>Puis sur la petite flèche après <code>Open in web IDE</code> et <code>Edit</code></li>
<li>Cliquer sur <code>Edit</code>
<ul>
<li>Remplacer à la dernière ligne 130 par 110</li>
<li>Commit changes</li>
<li><em>Le fichier a été modifié sur le dépôt distant</em></li>
</ul></li>
<li>Dans VSCode, éditer le fichier <code>voiture.py</code>
<ul>
<li>Remplacer à la dernière ligne 130 par 150 et enregistrer</li>
<li><code>git status</code>
<ul>
<li>le fichier <code>voiture.py</code> est à l’état modifié</li>
</ul></li>
<li><code>git commit -am "Modif vitesse max"</code></li>
<li><em>Le fichier a été modifié sur le dépôt local</em></li>
</ul></li>
<li><code>git push</code>
<ul>
<li>:warning: Error : petit piège, il faut toujours faire un pull avant de tenter un push</li>
<li>Le dépôt distant a été modifié</li>
<li>Je dois d’abord récupérer ces modifications sur mon dépôt local (pull)</li>
<li>Ensuite seulement je pourrai mettre à jour le dépôt distant (push)</li>
</ul></li>
<li><code>git pull</code>
<ul>
<li>:rotating_light: <em>Conflict - Automatic merge failed</em></li>
<li>Sur les 2 dépôts, la même ligne a été modifiée
<ul>
<li>Ainsi dans le cas présent, Git ne peut pas savoir quelle version choisir</li>
</ul></li>
<li>dans le terminal Git est au statut <strong><code>(main|MERGING)</code></strong></li>
</ul></li>
<li><code>git status</code>
<ul>
<li><em>both modified: <code>voiture.py</code></em></li>
</ul></li>
<li>Dans VSCode, ouvrir le fichier <code>voiture.py</code>, on voit s’afficher :</li>
</ul>
<pre class="python="><code>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD
        self.vitesse = min(150, self.vitesse + increment)
******=
        self.vitesse = min(110, self.vitesse + increment)
&gt;&gt;&gt;&gt;&gt;&gt;&gt; d29aa04e48e16d3648fd4ae9796b4a035e176f1c</code></pre>
<ul>
<li>Maintenant il faut choisir quelle ligne on garde
<ul>
<li>Celle du dessus est la notre (dépôt local)</li>
<li>Celle du dessous est celle telle qu’elle a été modifiée sur le dépôt distant</li>
</ul></li>
<li>Supprimer la ligne avec le 110, ainsi que les lignes avec <code>&lt;&lt;&lt;&lt;&lt;</code>, <code>****=</code> et <code>&gt;&gt;&gt;&gt;&gt;</code>
<ul>
<li>Ou cliquer simplement sur le bouton VSCode <code>Accept Current Change</code></li>
<li>Enregistrer</li>
</ul></li>
<li>:bulb: En théorie, à cet instant, il faut tester de nouveau que le programme fonctionne bien, cependant ce n’est pas l’objet de ce TP</li>
<li><code>git commit -am "Resolve merge"</code>
<ul>
<li>cela crée un nouveau point de sauvegarde pour valider le merge</li>
<li>dans le terminal Git repasse au statut <strong><code>(main)</code></strong></li>
</ul></li>
<li><code>git status</code></li>
<li><code>git push</code>
<ul>
<li>cette fois ci, c’est ok, les modifications faites sur le dépôt local sont poussées vers le dépôt distant</li>
</ul></li>
<li>:tada: Félicitations, vous venez de résoudre votre 1er conflit :champagne:
<ul>
<li>c’était pas compliqué, hein ?</li>
</ul></li>
</ul>
<hr>
<p>Les parties 3 et 4 sont de très loin les plus importantes. Pour utiliser efficacement Git, il faut impérativement avoir bien compris comment utiliser les 5 commandes principales (status, add, commit ,pull, push) et savoir résoudre des conflits.</p>
<p>La suite permet d’aller un peu plus loin si vous commencez à être à l’aise.</p>
<hr>
</section>
<section id="arrow_forward-5.-revenir-en-arrière" class="level2">
<h2 class="anchored" data-anchor-id="arrow_forward-5.-revenir-en-arrière">:arrow_forward: 5. Revenir en arrière</h2>
<p>:information_source: L’intérêt de versionner est d’avoir la possibilité de revenir en arrière si besoin !</p>
<p>Soyons clair, revenir en arrière n’est pas une action anodine et nécessite parfois une certaine maîtrise de Git. Nous nous contenterons donc ici de quelques outils de base.</p>
<hr>
<section id="small_orange_diamond-revenir-au-dernier-commit" class="level3">
<h3 class="anchored" data-anchor-id="small_orange_diamond-revenir-au-dernier-commit">:small_orange_diamond: Revenir au dernier commit</h3>
<p>Comme souvent avec Git, il y a plusieurs manières de faire, ici nous utiliserons la commande <code>stash</code></p>
<ul>
<li>Créer un fichier <code>vehicule.py</code></li>
<li>Modifier le fichier <code>voiture.py</code>
<ul>
<li>par exemple en ajoutant <code>toto</code> sur la dernière ligne</li>
</ul></li>
<li><strong><code>git stash -u</code></strong>
<ul>
<li>Le fichier <code>vehicule.py</code> a été supprimé</li>
<li>Le fichier <code>voiture.py</code> est revenu à l’état du dernier commit</li>
</ul></li>
<li>il est possible de retrouver les fichiers qui ont été “stashés” (voir commandes stash et pop)</li>
</ul>
<hr>
</section>
<section id="small_orange_diamond-consulter-lhistorique-dun-fichier" class="level3">
<h3 class="anchored" data-anchor-id="small_orange_diamond-consulter-lhistorique-dun-fichier">:small_orange_diamond: Consulter l’historique d’un fichier</h3>
<section id="dans-gitlab-aller-sur-le-fichier-voiture.py" class="level4">
<h4 class="anchored" data-anchor-id="dans-gitlab-aller-sur-le-fichier-voiture.py">Dans GitLab, aller sur le fichier <code>voiture.py</code></h4>
<ul>
<li>Cliquer sur History</li>
<li>Cela affiche la liste des commits qui ont mis à jour ce fichier</li>
</ul>
</section>
<section id="dans-git-bash" class="level4">
<h4 class="anchored" data-anchor-id="dans-git-bash">Dans Git Bash</h4>
<ul>
<li><code>git log voiture.py</code>
<ul>
<li>Cela affiche a peu près la même chose que dans GitLab
<ul>
<li>Faire <code>ENTREE</code> pour continuer à défiler</li>
<li>Faire <code>q</code> comme quit pour sortir</li>
</ul></li>
<li>Mais ce n’est pas très lisible, voire très moche</li>
<li>Heureusement la commande git log propose de nombreuses options</li>
</ul></li>
<li><code>git log</code> affiche une liste de commit
<ul>
<li>Pour la suite, nous ne limeterons pas aux commits impactant le fichier <code>voiture.py</code> mais nous afficherons tous les commits</li>
<li>vous pouvez ajouter à la fin de chaque commande le nom d’un fichier pour se restreindre aux commits sur ce fichier</li>
</ul></li>
<li><code>git log --pretty=format:'%C(yellow)%h %Cred%ad %Cblue%an%Cgreen%d %Creset%s' --date=relative</code>
<ul>
<li>C’est joli, non ?</li>
<li>Mais un peu pénible à retenir, et long à écrire</li>
<li>C’est ici que l’on présente les alias</li>
</ul></li>
<li>Voici deux commandes pour créer les alias nommés arbitrairement <code>bb</code> et <code>cc</code> :
<ul>
<li><code>git config --global alias.bb "log --pretty=format:'%C(yellow)%h %Cred%ad %Cblue%an%Cgreen%d %Creset%s' --date=relative"</code></li>
<li><code>git config --global alias.cc "log --all --decorate --oneline --graph"</code></li>
<li>ces 2 alias sont à créer une seule fois</li>
<li>éventuellement vous pouvez en créer d’autres, ou les modifier</li>
</ul></li>
<li>Maintenant essayez <code>git bb</code> et <code>git cc</code>
<ul>
<li>C’est de toute beauté !</li>
</ul></li>
</ul>
<hr>
</section>
</section>
<section id="small_orange_diamond-comparer-2-versions-dun-fichier" class="level3">
<h3 class="anchored" data-anchor-id="small_orange_diamond-comparer-2-versions-dun-fichier">:small_orange_diamond: Comparer 2 versions d’un fichier</h3>
<ul>
<li>Noter le numéro d’un commit où vous avez modifié <code>voiture.py</code>
<ul>
<li><code>git bb voiture.py</code></li>
<li>en jaune sur 7 caractères alphanumériques</li>
<li>ne choisissez pas le plus récent, sinon il n’y aura aucune différence</li>
</ul></li>
<li><strong><code>git diff 7539cf7 voiture.py</code></strong>
<ul>
<li>remplacer <code>7539cf7</code> par votre numéro de commit</li>
<li>vous voyez les différences la version actuelle et une ancienne version</li>
</ul></li>
<li><strong><code>git diff</code></strong>
<ul>
<li>pour lister toutes les modifications effectuées depuis le dernier commit</li>
<li><strong><code>git diff voiture.py</code></strong> : pour se limiter aux modifications effectuée sur ce fichier</li>
</ul></li>
</ul>
<hr>
</section>
<section id="small_orange_diamond-retour-vers-le-passé" class="level3">
<h3 class="anchored" data-anchor-id="small_orange_diamond-retour-vers-le-passé">:small_orange_diamond: Retour vers le passé</h3>
<ul>
<li>Toujours avec le numéro d’un ancien commit</li>
<li><strong><code>git checkout 7539cf7</code></strong>
<ul>
<li><em>HEAD is now 7539cf7</em></li>
<li>HEAD est un mot que l’on retrouve souvent dans Git
<ul>
<li>on peut le traduire par “tête de lecture”</li>
</ul></li>
<li>Au bout de la ligne de commande, ne s’affiche plus <code>(main)</code> mais <code>((7539cf7...))</code></li>
<li>Vous voici revenu au code tel qu’il était à l’époque de ce commit</li>
</ul></li>
<li><code>git checkout main</code> pour revenir au présent</li>
</ul>
<hr>
</section>
<section id="small_orange_diamond-annuler-un-commit" class="level3">
<h3 class="anchored" data-anchor-id="small_orange_diamond-annuler-un-commit">:small_orange_diamond: Annuler un commit</h3>
<ul>
<li>En fait non, on ne verra pas comment annuler un commit, ni sur le dépôt local, ni sur le dépôt distant. C’est possible mais à vos risques et périls.</li>
<li>Préférez la méthode un peu archaïque qui consiste à retourner dans le passé pour copier ce qui fonctionnait bien avant.</li>
<li>Et pour vous faciliter la vie, faites des commits réguliers et ne modifiez pas 50 fichiers dans un commit.</li>
</ul>
<p>:bulb: Si à un moment vous avez peur de faire une bétise et de perdre tout votre code (par exemple si une commande Git ne se passe pas comme vous l’aviez prévu), il est tout a fait possible de copier votre dépôt. Votre dépôt local est un dossier, allez dans l’explorateur windows, faites <code>CTRL + C</code> <code>CTRL + V</code> et voila vous avez une copie que vous pouvez garder de coté au cas où ça tourne mal.<br>
:bulb: Et surtout n’hésitez pas à demander de l’aide !</p>
<hr>
</section>
</section>
<section id="arrow_forward-fonctionnalités-de-gitlab" class="level2">
<h2 class="anchored" data-anchor-id="arrow_forward-fonctionnalités-de-gitlab">:arrow_forward: Fonctionnalités de GitLab</h2>
<p>GitLab n’est pas seulement un dépôt distant, il y a de nombreuses fonctionnalités interessantes.</p>
<ul>
<li>Issues : Pour lister et suivre les incidents ou les évolutions du programme</li>
<li>Wiki : Pour créer facilement des pages de documentation en langage markdown</li>
<li>CI/CD (Continuous Integration/Continuous Delivery) : Cela permet lorsque l’on met à jour le dépôt distant de lancer des tâches automatisées, par exemple pour : tester le code, évaluer la qualité du code, déployer le code sur une machine de production ou de développement…</li>
</ul>
<p>Voir un exemple avec <a href="https://gitlab.com/CalcProgrammer1/OpenRGB/-/wikis/home">ce projet</a></p>
<hr>
</section>
<section id="arrow_forward-un-petit-exo-dapplication" class="level2">
<h2 class="anchored" data-anchor-id="arrow_forward-un-petit-exo-dapplication">:arrow_forward: Un petit exo d’application</h2>
<ol type="1">
<li>Revenez dans VSCode, ouvrez un terminal Git Bash et positionnez votre terminal dans le dossier <code>P:\Cours\Python\git-tp</code> comme cela a été fait au début de la partie 2.</li>
<li>Dans VSCode, sur le constructeur de la classe <code>voiture</code>, mettre la valeur par défaut de couleur à <code>verte</code> : <code>def __init__(self, nom, couleur=verte)</code></li>
<li>Dans GitLab, faites la même modification sur la classe <code>voiture</code> mais en mettant cette fois-ci la couleur <code>jaune</code></li>
<li>Créez un nouveau fichier <code>velo.py</code> en copiant le contenu du fichier <code>voiture.py</code></li>
<li>Modifier la méthode <code>accelere()</code> de <code>velo.py</code> pour avoir une vitesse maximale de 80</li>
<li>Créer un point de sauvegarde sur votre dépôt local (add et commit)</li>
<li>Synchronisez vos dépôts et résolvez les conflits (pull et push)</li>
</ol>
<hr>
</section>
<section id="arrow_forward-les-branches" class="level2">
<h2 class="anchored" data-anchor-id="arrow_forward-les-branches">:arrow_forward: Les branches</h2>
<p>:information_source: Uniquement si vous êtes à l’aise</p>
<section id="small_orange_diamond-a-quoi-sert-une-branche" class="level3">
<h3 class="anchored" data-anchor-id="small_orange_diamond-a-quoi-sert-une-branche">:small_orange_diamond: A quoi sert une branche ?</h3>
<p>Imaginez vous avez votre code qui fonctionne bien mais qui est tout moche (avec des duplications…). Comme vous êtes sérieux, vous voulez faire tout bien comme il faut et mettre tout au propre.</p>
<p>Vous faites vos corrections, faites de commits, et puis à un moment vous en avez marre car plus rien ne fonctionne. Vous avez envie de retourner en arrière, ce qui est possible avec ce que l’on a vu précédemment mais pas trivial ni très propre.</p>
<p>Si vous connaissiez les branches voici ce que vous auriez fait :</p>
<ol type="1">
<li>créer une branche nommée “refonte”</li>
<li>Développer, Commiter sur cette branche</li>
<li>Si à la fin ce que vous avez fait sur cette branche vous plait alors fusion de cette branche avec la branche principale <strong>main</strong></li>
<li>Sinon vous pouvez simplement supprimer cette branche</li>
</ol>
<p>En gros une branche permet de coder et/ou tester une nouvelle fonctionnalité sans polluer la branche principale.</p>
<hr>
</section>
<section id="small_orange_diamond-un-petit-exemple-pour-y-voir-plus-clair" class="level3">
<h3 class="anchored" data-anchor-id="small_orange_diamond-un-petit-exemple-pour-y-voir-plus-clair">:small_orange_diamond: Un petit exemple pour y voir plus clair</h3>
<ul>
<li>imaginons que vous voulez ajouter une classe trottinette, mais vous n’êtes pas encore sûr, alors vous testez sur une branche</li>
<li><code>git checkout -b trottinette</code>
<ul>
<li>création d’une branche trottinette</li>
<li><em>Switched to a new branch ‘trottinette’</em>
<ul>
<li>et comme l’indique le message, avec cette commande vous êtes directement positionné sur cette branche</li>
</ul></li>
</ul></li>
<li>Créez un fichier <code>trottinette.py</code></li>
<li>Modifiez la vitesse de voiture à 210 parce que vous êtes un malade</li>
<li>add puis commit</li>
<li><code>git push</code> pour partager sur le dépôt distant
<ul>
<li>Git dit que cette branche n’est pas connue sur le dépôt distant</li>
<li>Mais comme il est sympa, il donne la commande pour la créer</li>
<li><code>git push --set-upstream origin trottinette</code></li>
</ul></li>
<li>Ensuite revenons sur la branche principale <code>main</code>
<ul>
<li><code>git checkout main</code></li>
</ul></li>
<li>Modifiez la vitesse maximale de voiture à 90 parce qu’en fait vous êtes très prudent puis commit</li>
<li>Maintenant, après mûre réflexion, vous vous dites que la trottinette c’est trop bien et qu’il faut l’intégrer à la branche main</li>
<li>Vous avec envie de fusionner directement les branches <code>trottinette</code> et <code>main</code>
<ul>
<li><code>git merge trottinette</code></li>
<li>Seulement il y a un conflit et c’est fait exprés</li>
<li>Il a été dit plus haut que la branche <strong>main</strong> doit rester le plus propre possible, ainsi on va éviter de la polluer avec des commits de gestion de conflit. Les conflits doivent être réglé sur les autres branches</li>
<li>Annulons ce merge
<ul>
<li><code>git merge --abort</code></li>
</ul></li>
</ul></li>
<li>Voici comment nous allons procéder pour faire cela proprement
<ul>
<li>On retourne sur la branche <code>trottinette</code>
<ul>
<li><code>git checkout trottinette</code></li>
</ul></li>
<li>Nous allons faire la fusion sur cette branche
<ul>
<li><code>git merge main</code></li>
<li>nous résolvons le conflit puis commit</li>
</ul></li>
<li>Maintenant que les 2 branches sont synchronisées, retournons sur la branche <code>main</code>
<ul>
<li><code>git checkout main</code></li>
<li><code>git merge --squash trottinette</code>
<ul>
<li>cette fois-ci pas de conflits car ils ont été résolu juste avant</li>
</ul></li>
<li><code>git commit -am "ajout fonctionnalité trottinette"</code></li>
</ul></li>
<li>L’option <code>--squash</code> permet de ne pas polluer le main avec tous les commits réalisés sur la branche <code>trottinette</code>. Si par la suite vous utilisez GitLab ou GitHub cette option se retrouve directement dans les merge ou les pull requests.</li>
</ul></li>
</ul>
<style>
    h1{
        color: darkblue;
        font-family: "Calibri";
        font-weight: bold;
        background-color: seagreen;
        padding-left: 10px;
    }
    h2{
        color: darkblue;
        background-color: mediumseagreen;
        margin-right: 10%;
        padding-left: 10px;
    }
    h3{
        color: darkblue;
        background-color: darkseagreen;
        margin-right: 20%;
        padding-left: 10px;
    }
    h4{
        color: darkblue;
        background-color: lightseagreen;
        margin-right: 30%;
        padding-left: 10px;
    }
    h5{
        color: darkblue;
        background-color: aquamarine;
        margin-right: 40%;
        padding-left: 10px;
    }
</style>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = true;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions"><ul><li><a href="https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau/edit/main/docs/outils/Git TP.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Website built with <a href="https://quarto.org/" target="_blank">Quarto</a><br> <a href="https://github.com/ludo2ne/ENSAI-2A-Big-Data" target="_blank">Source code</a></p>
</div>
  </div>
</footer>




</body></html>